query people {
  people {
    name
    email
    addresses {
      name
      street
    }
    tasks {
      label
      priority
      isComplete
    }
    images {
      name
      url
    }
  }
}

mutation createPerson($name: String, $email: String, $password: String) {
  createPerson(data: { name: $name, email: $email, password: $password }) {
    id
  }
}
